import json
import faiss
import logging
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import sys
import os

# --- CONFIGURATION ---
# 1. Import your settings and models
current_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.abspath(os.path.join(current_dir, "../../../.."))
sys.path.append(root_dir)
from core.config import settings 
from core.models import MedicalArticle 

# 2. Use the dynamically generated database URL
DATABASE_URL = settings.DATABASE_URL

# 3. Paths to the files generated by the pipeline
FAISS_INDEX_PATH = "../embeddings/faiss.index"
METADATA_PATH = "../embeddings/chunk_metadata.json"
# ---------------------

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
BATCH_SIZE = 500

def push_to_postgres():
    logging.info(f"Connecting to PostgreSQL at {settings.POSTGRES_SERVER}...")
    engine = create_engine(DATABASE_URL)
    SessionLocal = sessionmaker(bind=engine)
    session = SessionLocal()

    try:
        logging.info("Loading chunk metadata...")
        with open(METADATA_PATH, 'r') as f:
            metadata_records = json.load(f)

        logging.info("Loading FAISS index...")
        index = faiss.read_index(FAISS_INDEX_PATH)
        
        total_vectors = index.ntotal
        if total_vectors != len(metadata_records):
            raise ValueError(f"Mismatch! Found {total_vectors} vectors but {len(metadata_records)} JSON records.")

        logging.info("Extracting vectors from FAISS...")
        vectors = index.reconstruct_n(0, total_vectors)

        logging.info("Inserting records into PostgreSQL...")
        objects_to_insert = []

        for i in range(total_vectors):
            record = metadata_records[i]
            vector = vectors[i].tolist()

            source = record.get("source", "")
            pmid_val = record.get("metadata", {}).get("pmid", "")
            
            article_title = f"{source.capitalize()} Document - {pmid_val}" if pmid_val else f"{source.capitalize()} Document"
            article_url = f"https://pubmed.ncbi.nlm.nih.gov/{pmid_val}/" if pmid_val and source.lower() == "pubmed" else None

            metadata_tags = {
                "diseases": record.get("entities", {}).get("diseases", []),
                "drugs": record.get("entities", {}).get("drugs", []),
                "year": record.get("year"),
                "chunk_id": record.get("chunk_id", ""),
                "source": source
            }

            db_article = MedicalArticle(
                title=article_title,
                url=article_url,
                pmid=pmid_val,
                content=record.get("text", ""),
                metadata_tags=metadata_tags,
                embedding=vector
            )
            objects_to_insert.append(db_article)

            if len(objects_to_insert) >= BATCH_SIZE:
                session.bulk_save_objects(objects_to_insert)
                session.commit()
                objects_to_insert = []
                logging.info(f"Inserted {i + 1} / {total_vectors} chunks...")

        if objects_to_insert:
            session.bulk_save_objects(objects_to_insert)
            session.commit()

        logging.info("✅ Migration to PostgreSQL complete! The database is ready for vector search.")

    except Exception as e:
        session.rollback()
        logging.error(f"❌ Migration failed: {e}")
        raise
    finally:
        session.close()

if __name__ == "__main__":
    push_to_postgres()